### ISSUE TITLE
Parameter alignment

### ISSUE THREAD

**Issue by athlony2k** [tdesrosi/policy-library-tf-resource-change#1]
Shall we align the perameter value for 'mode' to allowlist, denylist across the sample constraints and templates?

for example:
in 'iam_allow_role.yaml', it's using the following:

parameters:
    mode: "allow"

**Comment by tdesrosi** [comment]
Fixed with commit: [464a34b](https://github.com/tdesrosi/policy-library-tf-resource-change/commit/464a34b54c54a2ec745422b2f4d63413373280de)
